version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  reviewers:
  - kpango
  - rinx
  labels:
  - type/dependency
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.37.19
    - 1.37.20
    - 1.37.21
    - 1.37.22
    - 1.37.24
    - 1.37.25
    - 1.37.26
    - 1.37.27
    - 1.37.28
    - 1.37.29
    - 1.37.30
    - 1.37.31
    - 1.37.32
    - 1.37.33
    - 1.38.0
    - 1.38.1
    - 1.38.11
    - 1.38.12
    - 1.38.13
    - 1.38.14
    - 1.38.15
    - 1.38.16
    - 1.38.17
    - 1.38.18
    - 1.38.19
    - 1.38.2
    - 1.38.20
    - 1.38.21
    - 1.38.22
    - 1.38.24
    - 1.38.25
    - 1.38.26
    - 1.38.3
    - 1.38.4
    - 1.38.5
    - 1.38.7
    - 1.38.8
    - 1.38.9
  - dependency-name: github.com/envoyproxy/protoc-gen-validate
    versions:
    - 0.4.1
    - 0.5.0
    - 0.5.1
    - 0.6.0
  - dependency-name: google.golang.org/api
    versions:
    - 0.41.0
    - 0.42.0
    - 0.43.0
    - 0.44.0
  - dependency-name: google.golang.org/grpc
    versions:
    - 1.36.0
    - 1.36.1
  - dependency-name: github.com/go-redis/redis/v8
    versions:
    - 8.7.0
    - 8.7.1
    - 8.8.0
  - dependency-name: cloud.google.com/go
    versions:
    - 0.78.0
    - 0.79.0
    - 0.80.0
  - dependency-name: github.com/kpango/glg
    versions:
    - 1.5.5
    - 1.5.7
