apiVersion: v1
entries:
  vald:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.028738571Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: c4ec1c737ece7e5f66a4f4e55648fbcff1cfa9ae57405a065a8047955e154d4b
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.18.tgz
    version: v0.0.18
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.024891108Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: eabfd9da9727a9fdabc879179df9e660915b693a800469af1fea861eedb23651
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.17.tgz
    version: v0.0.17
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.021037844Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: df734fc8c778639f72e236f3a6e5b9424511bbfaa29c4f5e805ccc8590b8780e
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.16.tgz
    version: v0.0.16
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.01536665Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: 05f0fd52428d9ed8d7ea342faeacc44995e7f45385997a27f4660b68067cd6f5
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.15.tgz
    version: v0.0.15
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.011198381Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: 62d06a8aa72da92ebf5420ea2ca4a65ae4c7424de10984f9217673fde8e37d6b
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.14.tgz
    version: v0.0.14
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.006850709Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: 4f2e58484324dfde7b964f7b4fe52b4e1b9c168900805559b8b4c808a382af65
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.13.tgz
    version: v0.0.13
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.001999529Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: b4b03e5ff29578eeb495750deff13e5e322e6e39bcaa3431be121ea157cd3369
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.12.tgz
    version: v0.0.12
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:29.997714358Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: b6ef538ea736096ee1aa51078998010cb3655c75bbb915de6ce5236cd7b782f6
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.11.tgz
    version: v0.0.11
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:29.992548672Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: 18e7fd5dbc900a660f38eb845f53f9a34a68d2e1e0419acdc177a394e860bbe2
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.10.tgz
    version: v0.0.10
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.053807286Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: 0d5d9da800193d2651396cfa9afbacb4877e8323b1a4ef2dfb6ddb9927a6c245
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.9.tgz
    version: v0.0.9
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.049523515Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: 48340b41f4eb17c6c9291f31d14daa83124ee43fe2d3bd876e7156f5206f6f0f
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.8.tgz
    version: v0.0.8
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.045289745Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: dad491638c9abe550bca1df24c2cfd3c9a99d5272c40c5c4a5a169c62cafca40
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.7.tgz
    version: v0.0.7
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.041394181Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: d8424275f550854062f4573c72b7d1b4059408cdfb92b3af5d80410b56aea868
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.6.tgz
    version: v0.0.6
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.037061509Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: 690df2ae4e3b5a92695f7b61bc38fc2d4b63ddf34a84f1e588110941bb20b06e
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.5.tgz
    version: v0.0.5
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-28T05:24:30.033283147Z"
    description: A distributed high scalable & high-speed approximate nearest neighbor
      search engine
    digest: ea9397e79f0b8fa6ab38bbcc133af30c9779d4660ee0f550026c0b8f2ac5f27a
    name: vald
    urls:
    - https://vald.vdaas.org/charts/vald-v0.0.4.tgz
    version: v0.0.4
generated: "2020-02-28T05:24:29.9882098Z"
